backend/backend/urls.py
from rest_framework import routers

from django.contrib import admin
from django.urls import include, path

import forum.views

api_router = routers.DefaultRouter()
api_router.register(r'forums', forum.views.ForumViewSet)
api_router.register(r'posts', forum.views.PostViewSet)
api_router.register(r'threads', forum.views.ThreadViewSet)
api_router.register(r'users', forum.views.UserViewSet)

urlpatterns = [
    path('control-panel/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/1/', include((api_router.urls, 'api'), namespace='api-v1')),

    path('', include('forum.urls')),
]

backend/forum/urls.py
from django.urls import include, path

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),

    path('forum/<int:id>/', views.forum_detail_by_id, name='forum-detail-by-id'),
    path('forum/<forum_slug>/', views.forum_detail_by_slug, name='forum-detail-by-slug'),

    path('thread/<int:id>/', views.thread_detail_by_id, name='thread-detail-by-id'),
    path('thread/<thread_slug>/', views.thread_detail_by_slug, name='thread-detail-by-slug'),

    path('forum/<forum_slug>/new-thread', views.thread_new_form, name='thread-new-form'),
    path('forum/<forum_slug>/new-thread-create', views.thread_create, name='thread-create'),
]

backend/forum/models.py
import json

from django.contrib.auth.models import AbstractUser
from django.db import models

import forum.lib as lib

class User(AbstractUser):
    pass


class Forum(models.Model):
    """
    A partition to group discussion topics together.
    """

    title = models.CharField(max_length=150, blank=False, null=False)
    slug = models.SlugField(max_length=60, unique=True, editable=False)
    description = models.CharField(max_length=500, default="Generic forum description")

    def save(self, *args, **kwargs):
        if not self.slug:
            lib.unique_slugify(self, self.title)
        super(Forum, self).save(*args, **kwargs)

    def __str__(self):
        return "(" + self.title + ") \"" + self.description + "\""


class Thread(models.Model):
    """
    Forum thread. A single topic of discussion.
    """

    title = models.CharField(max_length=500, blank=False, null=False)
    slug = models.SlugField(max_length=60, unique=True, editable=False)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    # TODO: what should behavior be when deleting a forum?
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE, blank=False, null=False)
    published = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    last_updated = models.DateTimeField(auto_now_add=True, verbose_name="date updated")

    def save(self, *args, **kwargs):
        if not self.slug:
            # need to parse title into JSON (because slatejs output is JSON)
            # yes, not very clean, I know...
            title_json = json.loads(self.title)
            lib.unique_slugify(self, title_json['document']['nodes'][0]['nodes'][0]['text'])
        super(Thread, self).save(*args, **kwargs)

    def __str__(self):
        return "(" + self.title + ") [" \
            + (self.author.username if self.author else "Anonymous") + "]"


class Post(models.Model):
    """
    Forum posts.
    """

    MAX_CHAR_LENGTH=50000
    PREVIEW_CHAR_LENGTH=30

    # TODO: on_delete=models.SET(<function to set author field to "deleted user">)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    content = models.TextField(max_length=MAX_CHAR_LENGTH)
    published = models.DateTimeField(auto_now_add=True, verbose_name="date published")

    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, blank=False, null=False)

    def __str__(self):
        model_text = "(" + (self.author.username if self.author else "Anonymous") + ") "
        model_text += self.content if len(self.content) < self.PREVIEW_CHAR_LENGTH \
            else (self.content[:self.PREVIEW_CHAR_LENGTH] + "...")
        return model_text

backend/forum/views.py
import json
import string

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from rest_framework import viewsets
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated

from .models import Forum, Post, Thread, User
from .serializers import ForumSerializer, PostSerializer, ThreadSerializer, UserSerializer


###############################################################################
# helpers
###############################################################################
def is_slate_value_empty(data):
    """
    Given a slate value serialized to JSON, return true if it's empty
    """
    try:
       value = json.loads(data)
    except json.JSONDecodeError:
        # if it's not JSON, it's plaintext
        return data == "" or data.isspace()

    doc_text = ""

    for block in value['document']['nodes']:
        doc_text += "".join([text['text'] for text in block['nodes']])

    return all(c.isspace() or c == "" or not (c in string.printable) for c in doc_text)


###############################################################################
# forum index                                                                 #
###############################################################################
def index(request):
    """
    This is the forums front page view. Show a list of all available forums.
    """
    context = {}
    context['forums'] = Forum.objects.order_by('id');
    return render(request, 'forum/index.html', context)


###############################################################################
# forum detail                                                                #
###############################################################################
def forum_detail_by_id(request, id):
    """
    View the contents of a specific forum.
    """
    forum = get_object_or_404(Forum, pk=id) 
    return _forum_detail(request, forum)


def forum_detail_by_slug(request, forum_slug):
    """
    View the contents of a specific forum (accessed by slug value)
    """
    forum = get_object_or_404(Forum, slug=forum_slug)
    return _forum_detail(request, forum)


def _forum_detail(request, forum):
    """
    View the contents of a specific forum (implementation)
    """
    context = {}
    context['forum'] = forum
    context['threads'] = Thread.objects.filter(forum=forum).order_by("-last_updated")
    return render(request, 'forum/forum.html', context)


###############################################################################
# thread detail                                                               #
###############################################################################
def thread_detail_by_id(request, id):
    """
    View the contents of a specific thread.
    """
    thread = get_object_or_404(Thread, pk=id)
    return _thread_detail(request, thread.forum, thread)
    

def thread_detail_by_slug(request, thread_slug):
    """
    View the contents of a specific thread. (accessed by slug value)
    """
    thread = get_object_or_404(Thread, slug=thread_slug)
    return _thread_detail(request, thread.forum, thread)


def _thread_detail(request, forum, thread):
    """
    View the contents of a specific thread.
    """
    context = {}
    context['thread'] = thread
    context['forum'] = forum
    context['posts'] = Post.objects.filter(thread=thread)
    return render(request, 'forum/thread.html', context)


###############################################################################
# thread create                                                               #
###############################################################################
def thread_new_form(request, forum_slug):
    """
    View to allow users to create a new thread.
    """
    context = {}
    context['forum'] = get_object_or_404(Forum, slug=forum_slug)
    return render(request, 'forum/thread_new_form.html', context)


def thread_create(request, forum_slug):
    """
    
    """
    raise NotImplementedError(
        "TODO: Implement 'thread-create' endpoint (%s)"
        % reverse('forum:thread-create', kwargs = { 'forum_slug': forum_slug })
    )


###############################################################################
# REST api views                                                              #
###############################################################################
class ForumViewSet(viewsets.ModelViewSet):
    """
    API endpoing for viewing and editing forums.
    """
    queryset = Forum.objects.all().order_by('id')
    serializer_class = ForumSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.

        Only Admin users can modify User objects, although anyone can
        list and view them.
        """
        if (self.action == 'create'
        or self.action == 'update'
        or self.action == 'partial_update'
        or self.action == 'destroy'):
            permission_classes = [IsAdminUser]
        else:
            permission_classes = [AllowAny]

        return [permission() for permission in permission_classes]


# TODO: Probably want to have even more granular permissions between anonymous
# and logged in users. For example, anonymous users may be rate limited for
# creating posts, but logged in users are not.
class PostViewSet(viewsets.ModelViewSet):
    """
    API endpoing for viewing and editing forum posts
    """
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if (self.action == 'update'
        or self.action == 'partial_update'
        or self.action == 'destroy'):
            # TODO: we actually want to enable Object level permissions here and
            # let anonymous (and authenticated) users edit or delete their own
            # posts but none of the other ones.
            permission_classes = [IsAuthenticated]
        else:
            permission_classes = [AllowAny]

        return [permission() for permission in permission_classes]

    def create(self, request, *args, **kwargs):
        """
        Upon creating a new post, do the default action, but we also
        need to update the `last_updated` field of the Thread object
        this belongs to.
        """
        if is_slate_value_empty(request.data['content']):
            return JsonResponse({'error': 'Cannot create an empty post.'})

        response = super().create(request, *args, **kwargs)
        post = Post.objects.get(pk = response.data["id"])
        post.thread.last_updated = timezone.localtime()
        post.thread.save()
        return response

    def update(self, request, *args, **kwargs):
        """
        Make sure that the new post is not empty
        """
        if is_slate_value_empty(request.data['content']):
            return JsonResponse({'error': 'Cannot create an empty post.'})

        response = super().update(request, *args, **kwargs)
        post = Post.objects.get(pk = response.data["id"])
        post.thread.last_updated = timezone.localtime()
        post.thread.save()
        return response

    def partial_update(self, request, *args, **kwargs):
        if is_slate_value_empty(request.data['content']):
            return JsonResponse({'error': 'Cannot create an empty post.'})

        response = super().partial_update(request, *args, **kwargs)
        post = Post.objects.get(pk = response.data["id"])
        post.thread.last_updated = timezone.localtime()
        post.thread.save()
        return response


class ThreadViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows threads to be viewed or edited
    """
    queryset = Thread.objects.all()
    serializer_class = ThreadSerializer

    def get_permissions(self):
        """
        Instantiates and returns a list of permissions that this view requires.
        """
        if (self.action == 'update'
        or self.action == 'partial_update'
        or self.action == 'destroy'):
            # TODO: we actually want to enable Object level permissions here and
            # let anonymous (and authenticated) users edit or delete their own
            # posts but none of the other ones.
            permission_classes = [IsAdminUser]
        else:
            permission_classes = [AllowAny]

        return [permission() for permission in permission_classes]

    def create(self, request, *args, **kwargs):
        """
        Make it so that you can't create a thread without supply the contents
        of the first post as well.
        """
        if is_slate_value_empty(request.data['content']):
            return JsonResponse({'error': 'Cannot create a Thread with an empty OP.'})

        if is_slate_value_empty(request.data['title']):
            return JsonResponse({'error': 'Cannot create a Thread with an no title.'})

        response = super().create(request, *args, **kwargs)

        # get this thread object
        thread = Thread.objects.get(pk = response.data['id'])

        # make a new post
        post = Post(content=request.data['content'], thread=thread)
        post.save()

        return response


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.

        Only Admin users can modify User objects, although anyone can
        list and view them.
        """
        if (self.action == 'create'
        or self.action == 'update'
        or self.action == 'partial_update'

backend/forum/templates/forum/forum.html
{% extends 'forum/template_page_default.html' %}
{% load formatting_filters %}

{% block header %}
   <head>
      <title>SP Forum :: {{ forum.title }}</title>
   </head>
{% endblock header %}

{% load breadcrumbs %}
{% block breadcrumbs %}
   {% breadcrumb 'Home' 'forum:index' %}
   {% breadcrumb forum.title %}
{% endblock breadcrumbs %}

{% block content %}
   <div class="pre_threads_list">
      <h1>{{ forum.title }}</h1>
      <h4>{{ forum.description }}</h4>

      <a class="new_thread_button" href="{% url 'forum:thread-new-form' forum_slug=forum.slug %}">New Thread</a>
   </div>

   <table class="threads_list">
      <thead>
         <tr>
            <th class="threads_list_header">Threads</th> 
            <th class="threads_list_header">OP</th>
         </tr>
      </thead>
      <tbody>
         {% for thread in threads %}
            <tr>
               <td class="threads_list_data">
                  <a href="{% url 'forum:thread-detail-by-slug' thread_slug=thread.slug %}">
                     {{ thread.title|format_rich }}
                  </a>
               </td>
               <td class="threads_list_data">{{ thread.author.username|default:"Anonymous" }}</td>
            </tr>
         {% empty %}
            <tr><td class="threads_list_data">There are no threads...</td></tr>
         {% endfor %}
      </tbody>
   </table>
{% endblock content %}

backend/forum/templates/forum/index.html
{% extends 'forum/template_page_default.html' %}

{% load breadcrumbs %}
{% block breadcrumbs %}
   {% breadcrumb 'Home' '' %}
{% endblock breadcrumbs %}

{% block content %}
   <article>
      <table class="forums_list">
         <thead>
            <tr>
               <th class="forums_list_header">Topics</th>
               <th class="forums_list_header"></th>
            </tr>
         </thead>
         <tbody>
            {% for forum in forums %}
               <tr>
                  <td class="forums_list_data"><a href="{% url 'forum:forum-detail-by-slug' forum_slug=forum.slug %}">{{ forum.title }}</a></th>
                  <td class="forums_list_data">{{ forum.description }}</td>
               </tr>
            {% empty %}
               <tr><td class="forums_list_data">There are no forums...</td></tr>
            {% endfor %}
         </tbody>
      </table>
   </article>
{% endblock content %}

backend/forum/templates/forum/template_page_default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   {% block header %}
      <head>
         <title>SP Forum</title>
      </head>
   {% endblock header %}

   <body>
      {% block header_formatting %}
         <div class="header">
            <div class="header_content">
               <header>
                  {% block header_content %}
                     <h1 class="logo">SP Forums</h1>
                  {% endblock header_content %}
               </header>
            </div>
         </div>
      {% endblock header_formatting %}

      {% block second_header_formatting %}
         <div class="second_header">
            <div class="second_header_content">
               {% block second_header_content %}
               {% endblock second_header_content %}
            </div>
         </div>
      {% endblock second_header_formatting %}

      <div class="body_wrapper">
         {% block backing %}
            <div class="backing"></div>
         {% endblock backing %}

         <div class="main_content">
            <div class="pre_main_content">
               <ul class="breadcrumb-container">
                  {% block breadcrumbs %}
                  {% endblock breadcrumbs %}
               </ul>
            </div>

            {% block content %}
            {% endblock content %}
         </div>
      </div>

      <div class="footer">
         {% block footer_formatting %}
            {% block footer_content %}
            {% endblock footer_content %}
         {% endblock footer_formatting %}
      </div>

      {% block scripts %}
         {% load render_bundle from webpack_loader %}
         {% render_bundle 'main' %}

         <script>
            forum_js.deserialize_slate_content();
         </script>
      {% endblock %}
   </body>
</html>

backend/forum/templates/forum/thread.html
{% extends 'forum/template_page_default.html' %}
{% load formatting_filters %}

{% block header %}
   <head>
      <title>SP Forum :: {{ thread.title|format_plain }}</title>
   </head>
{% endblock header %}

{% load breadcrumbs %}
{% block breadcrumbs %}
   {% breadcrumb 'Home' 'forum:index' %}
   {% breadcrumb forum.title 'forum:forum-detail-by-slug' forum_slug=forum.slug %}
   {% breadcrumb thread.title|format_plain %}
{% endblock breadcrumbs %}

{% block content %}
   <h1>{{ thread.title|format_rich }}</h1>
   <h3>OP: {{ thread.author|default:"Anonymous" }}</h3>

   <table class="posts_list">
      <tbody>
         {% for post in posts %}
            <tr>
               <th class="posts_list_header">{% if post.author %}{{ post.author.username }}{% else %}Anonymous{% endif %}</th>
               <td class="posts_list_data">{{ post.content|format_rich }}</td>
            </tr>
         {% empty %}
            <tr><td class="posts_list_data">There are no posts in this thread...</td></tr>
         {% endfor %}

         <tr>
            <!-- TODO: replace this with new post meta information -->
            <th class="posts_list_header">{% if post.author %}{{ post.author.username }}{% else %}Anonymous{% endif %}</th>
            <td class="posts_list_data">
               <div id="editor-area">
                  TODO: implement non-javascript version
               </div>
            </td>
         </tr>
      </tbody>
   </table>
{% endblock content %}

{% block scripts %}
   {% load render_bundle from webpack_loader %}
   {% render_bundle 'main' %}

   <script>
      // set up editor variables
      props = {
         id: 'editor-area',
         action: "{% url 'api:post-list' %}",
         onSubmitPost: function(event, editor, response) {
            // add new post contents to page after request is complete
            response.json().then(function(data) {
               if (data.error) {
                  alert(data.error);
                  return false;
               }

               var post_list = document.getElementsByClassName("posts_list")[0];
               var num_rows = post_list.getElementsByTagName("tr").length;
               var new_post = post_list.insertRow(num_rows - 1);

               var post_info = document.createElement('th');
               var post_content = new_post.insertCell(0);

               post_content.insertAdjacentElement("beforebegin", post_info);

               post_info.classList.add("posts_list_header");
               post_content.classList.add("posts_list_data");

               post_info.innerHTML = data.author ? data.author.username : "Anonymous";
               post_content.innerHTML = "<span class=\"format_rich\">" + data.content + "</span>";
            })
            .then(forum_js.deserialize_slate_content);
         },
         post: {
            thread: "{{ thread.id }}",
         },
      }

      // mount editor on DOM
      forum_js.load_editor(props);

      // deserialize any tagged slate content
      forum_js.deserialize_slate_content();
   </script>
{% endblock scripts %}

backend/forum/templates/forum/thread_new_form.html
{% extends 'forum/template_page_default.html' %}

{% block header %}
   <head>
      <title>SP Forum :: New Thread</title>
   </head>
{% endblock header %}

{% load breadcrumbs %}
{% block breadcrumbs %}
   {% breadcrumb 'Home' 'forum:index' %}
   {% breadcrumb forum.title 'forum:forum-detail-by-slug' forum_slug=forum.slug %}
   {% breadcrumb 'Create New Thread' %}
{% endblock breadcrumbs %}

{% block content %}
   <!-- TODO: figure out how to style this -->
   <div id="title-editor">TODO: non-javascript title here?</div>
   <h3>OP: {{ thread.author|default:"Anonymous" }}</h3>

   <table class="posts_list">
      <tbody>
         <tr>
            <!-- TODO: replace this with new post meta information -->
            <th class="posts_list_header">{% if post.author %}{{ post.author.username }}{% else %}Anonymous{% endif %}</th>
            <td class="posts_list_data">
               <div id="post-editor">
                  TODO: implement non-javascript version..., BIIIIITCH
               </div>
            </td>
         </tr>
      </tbody>
   </table>

{% endblock content %}

{% block scripts %}
   {% load render_bundle from webpack_loader %}
   {% render_bundle 'main' %}

   <script>
      // set up editor variables for title editor (we will not be submitting this)
      title_props = {
         has_status_bar: false,
         id: 'title-editor',
         placeholder: "Enter a thread title",
         onKeyDown: function(event, editor, next) {
            // detect Android OS
            if (navigator.userAgent.toLowerCase().indexOf("android") > -1) {
               return;
            }

            // prevent users (desktop and Android Chrome) from pressing enter in this editor
            if (event.keyCode === 13) {
               event.preventDefault();
               event.stopPropagation();
            }

            // 8 is backspace and 46 is delete
            const delta = (event.keyCode === 8 || event.keyCode === 46 ? -1 : 1);
            const block0_len = editor.state.block0_len ? delta + editor.state.block0_len : Math.max(0, delta);

            // drop input if max length is reached
            if (block0_len > 200) {
               event.preventDefault();
               event.stopPropagation();
            } else {
               editor.setState({ block0_len });
            }
         },
      };

      // mount title editor on DOM
      const title_editor = forum_js.load_editor(title_props);

      // set up editor variables for post editor
      main_editor_props = {
         action: "{% url 'api:thread-list' %}",
         id: 'post-editor',
         onSubmit: function(event, editor, response) {
            // data to send through POST
            const post_data = {
               title: JSON.stringify(title_editor.state.value.toJSON()),
               forum: editor.props.post.forum,
               content: JSON.stringify(editor.state.value.toJSON()),
            };

            return post_data;
         },
         onSubmitPre: function(event, editor, response) {
            // detect Android OS
            if (navigator.userAgent.toLowerCase().indexOf("android") > -1) {
               // if we're on Android, collect the content editable and deserialize it
               // to a slate value as a hack
               const html = new forum_js.Html({ rules: forum_js.rules });
               const value = html.deserialize(document.getElementById(title_editor.props.id).firstChild.innerHTML);

               title_editor.state.value = value;
            }
         },
         onSubmitPost: function(event, editor, response) {
            function get_thread_details(thread_id) {
               return "{% url 'api:thread-detail' pk=1337 %}".replace('1337', thread_id);
            }

            function get_thread_page(thread_slug) {
               return "{% url 'forum:thread-detail-by-slug' thread_slug=1337 %}"
                  .replace('1337', thread_slug);
            }

            response.json().then(function(data) {
               if (data.error) {
                  alert(data.error);
                  return false;
               }

               return fetch(get_thread_details(data.id));
            })
            .then(function(response) {
               if (response === false) {
                  return;
               }

               response.json().then(function(data) {
                  // redirect to new thread page
                  window.location.replace(get_thread_page(data.slug));
               });
            })
         },
         post: {
            thread: "{{ thread.id }}",
            forum: "{{ forum.id }}",
         },
      }

      // mount post editor on DOM
      forum_js.load_editor(main_editor_props);
   </script>
{% endblock scripts %}